### ISSUE TITLE
Migrate all CSS to LESS

### ISSUE THREAD

**Issue by dirkgroenen** [dirkgroenen/mopidy-mopify#93]
Mopify started as an experimental project so some of the code/css/html is quite dirty. This needs to be cleaned up somewhere in the road.

**Comment by chookies** [comment]
Have you considered [Sass](http://sass-lang.com/) too?

I'm willing to pick this up, if you're not already working on it.

**Comment by dirkgroenen** [comment]
I'm still more of a LESS fan. Partly because it's already integrated in most of my Grunt tasks (and therefore easy to integrate in the current Gruntfile) and because I've been using it first. 

At the moment I'm working on the Local Files and other things around V2.0 #113. It would be awesome if you would pick this one up. If you want I can also add some extra tasks to the Gruntfile so you don't have to get into that when using LESS.

**Comment by chookies** [comment]
I have some experience with Grunt, so that's no problem. If you insist on Less, I'll do that, although Sass has some great advantages ;) (see [this comparison](https://css-tricks.com/sass-vs-less/) for example)

**Comment by dirkgroenen** [comment]
Yes I would prefer using LESS for it's easy to implement in the current workflow. I know SASS has some great advantages, but to be honest: most of the things I'm doing with LESS work just fine. 

I don't want to drop SASS completely from the table in general, but for this case it just doesn't seem the 'best choice'.

**Comment by chookies** [comment]
I've started migrating to Less and it's looking pretty good so far. I'm breaking down the `50-style.css` file into independent components to make them more maintainable (you can see the result up until now in my fork, development branch, but it's still a work in progress, let me know if there's anything off).

Because Less has mixins, I added a library to bower called [lesshat](http://lesshat.madebysource.com/) for mixins like `.transition()` and `border-radius-top-left()` etc.

Bootstrap and responsive are yet to be done. The former should be easy, because bootstrap supports less with variables. 

One other thing: when opening the app, there's some volume overlay that blocks the entire page. I'm assuming that's a work in progress, but for development purposes I've hidden that element temporarily with the following css:

```less
.volumeoverlay, .bgimage {
    display: none;
}
```

**Comment by dirkgroenen** [comment]
Nive work mate, I appreciate this! Personally I'm a fan of formatting the blocks with an extra line break before each new nested block, but that's a personal preference. I'm already happy that you've picked this issue up. :+1: 

The ``.volumeoverlay`` is used in the responsive version of the app. It should be an overlay over the complete page which is hidden by default using Angular's `ng-hide` class. 

![](http://i.imgur.com/XZsLgZN.png)

**Comment by chookies** [comment]
Yeah, that's my preference too, but I missed a few spots ;)

**Comment by dirkgroenen** [comment]
In that case I've said nothing. Keep up the good work :+1:

**Comment by koenpunt** [comment]
I'm not sure if it's the case here, but what I still see a lot is people using mixins for `border-radius` and `box-shadow` (and others). But the browsers that currently support these, will support them without vendor prefixes. So please make sure you're actually in need of those mixins. 
To circumvent the use of vender mixins, I suggest using [autoprefixer](https://github.com/postcss/autoprefixer) instead.

**Comment by koenpunt** [comment]
Nb. you can use autoprefixer easily with Grunt: https://github.com/postcss/autoprefixer#grunt

**Comment by dirkgroenen** [comment]
I leave this one up to @chookies. Looking at the Analytics stats we don't necessarily have to use it:

![image](https://cloud.githubusercontent.com/assets/1001391/8700840/89c5ea14-2b0e-11e5-94f5-0e03811ccaaf.png)

**Comment by chookies** [comment]
@dirkgroenen: I've done some more work on migrations (see my fork), but I'm hesitant to make a pull request yet, because there are some issues left:

- Bootstrap is generated from a config file. Because Bs is built on less, we could add it as a bower dependency and let our less files include the right Bs files. I'm not sure how this is done right, because I wasn't able to find documentation on this yet, so I need to look into that a bit more.

- I haven't tested everything thoroughly yet, although I noticed a regression with the original css: the mediaplayer at the bottom doesn't align right, but I couldn't find a cause. Maybe if you look at the less files you'll see it right away.

**Comment by koenpunt** [comment]
@chookies good effort so far! But I noticed you make extended use of nesting, which may look appealing in the LESS file, but when compiled to CSS it will result in massive selectors, which will definitely slow down rendering. 
And in combination with the use of id's, overriding selectors is a tedious task.

Personally I only use nesting for states and dependent child elements (icons in buttons, etc).

```less
.btn {
  color: #000;
  &:hover {
    color: #f00;
  }
  &:active,
  &:focus {
    color: #ff0;
  }
}

.btn-blue {
  color: #00f;
}

.btn-icon {
  text-indent: -100%;
  .icon {
    content: "...";
  }
}
```
Less specific selectors are often better, and also easier to override. 

But that are just my 2-cents

**Comment by chookies** [comment]
Thanks for your feedback. I'll refactor it to use less nesting (no pun intended). I already removed plenty of nesting caused by multiple ids in one selector, which is unnecessary afaik. The main.less file still has some very specific selectors that need to be migrated.

**Comment by koenpunt** [comment]
A better example would be when using lists (`ul`'s), I often see things like:

```less
.navigation {
  ul {
    padding: 5px;
    margin: 0;
    li {
      display: inline-block;
      a {
        display: block;
        padding: 10px;
        border: 1px solid #f00;
      }
    }
  }
}
```

But an `li` always is a child of an `ul`, so there's no need of putting it inside of the `ul` selector:

```less
.navigation {
  ul {
    padding: 5px;
    margin: 0;
  }
  li.nav-item {
    display: inline-block;
    a {
      display: block;
      padding: 10px;
      border: 1px solid #f00;
    }
  }
}
```

And also, as probably all links in the navigation element are a part of the list, that `a` doesn't have to sit in that `li` (I know, this is not exactly like the `ul`/`li` dependency, and more dependent on the actual HTML):

```less
.navigation {
  ul {
    padding: 5px;
    margin: 0;
  }
  li {
    display: inline-block;
  }
  a {
    display: block;
    padding: 10px;
    border: 1px solid #f00;
  }
}
```
